apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-platform-api
  labels:
    app: production-platform-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: production-platform-api
  template:
    metadata:
      labels:
        app: production-platform-api
    spec:
      containers:
        - name: production-platform-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
