replicaCount: 1

image:
  repository: ghcr.io/fiyinadedigba/production-platform-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000
