
services:
  postgres:
    image: postgres:15
    container_name: incidents-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incidents
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
