apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-platform-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/fiyinadedigba/production-platform-api
    argocd-image-updater.argoproj.io/api.update-strategy: semver
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/api.pull-secret: secret:argocd/ghcr-creds#creds
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default

  source:
    repoURL: https://github.com/fiyinadedigba/production-platform-lab.git
    targetRevision: main
    path: infrastructure/kubernetes/helm/production-platform-api

    helm:
      values: |
        image:
          repository: ghcr.io/fiyinadedigba/production-platform-api
          tag: v1.0.6

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
